In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.rand(2)

array([0.64567356, 0.3661724 ])

In [20]:
np.random.rand(5,5)

array([[0.97367937, 0.36806411, 0.53340286, 0.94592598, 0.65543079],
       [0.36706779, 0.73115867, 0.52948466, 0.66999146, 0.91397148],
       [0.47554478, 0.06389584, 0.81300408, 0.21864974, 0.96993112],
       [0.08058306, 0.46572761, 0.00254221, 0.95689386, 0.86528223],
       [0.28753317, 0.97968782, 0.11736648, 0.39895581, 0.89652203]])

In [21]:
np.random.randn(2)

array([-1.65724112, -0.16186326])

In [22]:
np.random.randn(5,5)

array([[-0.19838225, -1.6359152 ,  0.78755294,  0.37071509,  0.983019  ],
       [ 0.46288853,  0.44412215, -0.3403167 , -1.53913335,  0.90023974],
       [ 2.45861054,  0.9389574 ,  0.1816109 , -0.67578147, -1.25992304],
       [-1.25521615,  0.31281074,  1.90317565,  0.03383144, -0.60761608],
       [-0.79877767, -1.36192515,  1.06578508, -0.11398229,  0.43129152]])

In [23]:
np.random.randint(1,100)

36

In [26]:
np.random.randint(1,5,10)

array([1, 3, 4, 2, 2, 4, 2, 2, 1, 4])

In [27]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
ranarr

array([24, 38, 40, 11, 27,  1, 21, 41, 24, 14])

In [30]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
ranarr

array([24, 38, 40, 11, 27,  1, 21, 41, 24, 14])

In [32]:
ranarr.max()

41

In [33]:
ranarr.argmax()

7

In [34]:
ranarr.min()

1

In [35]:
ranarr.argmin()

5

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
arr = np.arange(0,11)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr[8]

8

In [40]:
arr[1:5]

array([1, 2, 3, 4])

In [41]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [42]:
arr[0:5]= 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [43]:
arr = np.arange(0,11)

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
slice_arr = arr[0:6]

In [46]:
slice_arr

array([0, 1, 2, 3, 4, 5])

In [47]:
slice_arr[:]=99
slice_arr

array([99, 99, 99, 99, 99, 99])

In [48]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [49]:
arr_copy = arr.copy()

In [50]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [51]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [52]:
arr_2d[1]

array([20, 25, 30])

In [56]:
arr_2d[1,0]

20

In [59]:
arr_2d[2:]

array([[35, 40, 45]])

In [60]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [73]:
arr =  np.arange(0,11)

In [74]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
arr >4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [76]:
boolarr = arr>4

In [77]:
boolarr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [78]:
arr[boolarr]

array([ 5,  6,  7,  8,  9, 10])

In [79]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [83]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [84]:
arr/arr

C:\Users\Hp\AppData\Local\Temp\ipykernel_7568\1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [86]:
1/arr

C:\Users\Hp\AppData\Local\Temp\ipykernel_7568\255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [87]:
arr*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [88]:
arr**3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [89]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [90]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [91]:
np.max(arr)

10

In [92]:
np.log(arr)

C:\Users\Hp\AppData\Local\Temp\ipykernel_7568\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])